version: '3.8'

services:
  frontend:
    image: todo-frontend
    stdin_open: true
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    command: npm run dev
  backend:
    image: todo-backend
    stdin_open: true
    tty: true
    ports:
      - 3003:3003
    volumes:
      - ./backend:/app
    environment:
      DB_URL: mongodb://db/todo
    depends_on:
      - db
    command: npm run dev
  db:
    image: mongo:4.4.29
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db

